### PR TITLE
Unit Tests: getUsersById, getUsersByName, postComment

### PR DESCRIPTION
**Pull request by Dendrobyte**
All unit tests functional:
image

Note on `getUsersByName`... the only time that route is called, only one name is passed in as a string. The route doesn't take an array of users. In the event that changes, the test is very easy to modify.

### CODE REVIEW

**Comment by Dendrobyte** [comment]
typo fix
image

**Review by amn493 — CHANGES_REQUESTED** [review]
A few things...

`postComment.test.js`:
- Maybe test the response's values to make sure they match the ones from `mockComment`
- You need to delete the comment after each test (could use an `afterEach` and just delete the document using the _id from the response)

`getUsersByName.test.js`:
- You don't really need to get 3 users (you only seem to be using one)
- You should have tests for sending each of the following: `username`, `firstName`, `lastName`
- Check to make sure that all of the users in the response arrays match the `name` in at least one of the three fields

**Comment by Dendrobyte** [comment]
image

**Review by amn493 — CHANGES_REQUESTED** [review]
`getUsersByName.test.js`:
- The last unit test doesn't need an else because the if should work regardless
- Also, all of the tests should look like the last one - it doesn't really make sense to have tests that just check the first user since this route is usually expected to return more than one user

**Review by amn493 — APPROVED** [review]
Fixed!

**Pull request merged**
