### PR TITLE
Front-end edit profile form

### PR DESCRIPTION
**Pull request by Dendrobyte**
Front-end form for the edit profile page completed.

### CODE REVIEW

**Comment by Dendrobyte** [comment]
image

**Comment by Dendrobyte** [comment]
Make browse an actual browse function then good to merge

**Comment by Dendrobyte** [comment]
image

**Comment by amn493** [comment]
- Make sure that the text fields are editable by using state variables and onChange handlers
- Use `bs-custom-file-input` to display the selected file name

**Review by amn493 — APPROVED** [review]

**Pull request merged**
