### PR TITLE
Fixing postNotificationSettings.test.js

### LINKED ISSUE #471: Update postNotificationSettings.test.js

### PR DESCRIPTION
**Pull request by JonathanSussman1**
- resolves #471

### CODE REVIEW

**Review by Dendrobyte — COMMENTED** [review]
I think it looks good, but I'm getting the following TypeError:
image

If it's just something on my end lmk and I'm happy to approve! The rest looks good, just want to triple confirm that the TypeError isn't something bad.

**Comment by JonathanSussman1** [comment]
> I think it looks good, but I'm getting the following TypeError:
> image
> 
> If it's just something on my end lmk and I'm happy to approve! The rest looks good, just want to triple confirm that the TypeError isn't something bad.

It seems to be coming from a call to multer in app.js, which this test doesn't make any calls to. I'm assuming it shows up in the `npm test` output as some sort of residue from the failing POST /comment unit test that is run directly beforehand? Because when I run the tests individually with `mocha test/postNotificationSettings.test.js` the error doesn't show up. But this is a weird thing that maybe we can discuss during workshop today.

**Comment by JonathanSussman1** [comment]
I just commented out the POST /comments unit tests and don't get the error anymore in the output of `npm test`. I think the error is printed after the "Testing POST to /notificationsettings API" line in terminal because the async operations in `before()` function for the /notificationsettings tests are run before stderr from some postComment.test.js process is closed? I could try to block this from happening, but I feel like it'd be overkill right now considering it shouldn't happen anymore once those POST /comments tests are fixed. Let me know if good to merge

**Review by anvitayella — APPROVED** [review]
If the issue if with the /comments test, I think you're good to merge since that will be fixed soon.

**Pull request merged**
