### PR TITLE
Setting up SMTP connection for sending email notifications and implementing send email notifications for liked recipes

### LINKED ISSUE #360: Send email notifications upon follow, like, and comment depending on user's settings (User Story #359)
1. When POST request is made to /followuser and `follow` is true send email to user being followed
2. When POST request is made to /likerecipe and `like` is true send email to recipe author
3. When POST request is made to /comment send email to recipe author
4.  expect user being followed email address and user's username, user's relevant notification setting

### PR DESCRIPTION
**Pull request by JonathanSussman1**
- Setting up credentials and SMTP connection for sending email notifications from recipeboxupdate@gmail.com
- Actually allowing notifications to be sent for liked recipes

### CODE REVIEW

**Comment by amn493** [comment]
Writing "resolves" will close the task when this pr is merged

**Review by amn493 — CHANGES_REQUESTED** [review]
You need to commit `package.json` and `package-lock.json` in order to add the new dependency

**Review by amn493 — COMMENTED** [review]
Comparing the user objects won't properly test equality, since technically they are different objects, despite having identical fields and values. I recommend comparing the `_id`s. Also, in the email body, can you add `@` before the username?

**Review by amn493 — APPROVED** [review]
Works great!

**Comment by Dendrobyte** [comment]
Seeing all the email stuff done and working is giving me those "wow this project is really coming to life" vibes. Very epic 🙌

**Pull request merged**
