### PR TITLE
Added feed page and put it in app.js

### LINKED ISSUE #18: Page(s): Feed page (This task is part of User Story #25)

### PR DESCRIPTION
**Pull request by Dendrobyte**
Incomplete until I'm able to bring in the mockaroo mock data from the big recipes, so not ready to merge, but ready to review (in theory).

CSS will also need some work, as with everything else, but I made the background `azure` for now and a lot of it will be done in BigRecipePreview as well. resolves #18 

Wrapped in `container` class to center responsively.

### CODE REVIEW

**Comment by Dendrobyte** [comment]
Resolves #18

**Comment by Dendrobyte** [comment]
Started working on recipebox and realized it would be best to have a component that just shows a feed of queued recipes, since the large and small previews don't have specific styles within the tags for the external div (plus repeat of for loop).

So this is going to depend on #79 and will be updated when that is merged

**Comment by amn493** [comment]
The width seems to be being constrained in the css, however all pages are already constrained within App.css. This is causing an additional constraint, which is making the components in this page too narrow.

**Review by amn493 — APPROVED** [review]
Looks good to me! Feel free to merge

**Pull request merged**
