### PR TITLE
Feed Page pulls from database

### PR DESCRIPTION
**Pull request by Dendrobyte**
- Will not run unless `FollowButton.js` has the import added back in (going to check that PR right after I write this), but once that is imported (or done manually on your end) it runs fine.

Additions:
- `/feedrecipes` will load recipes posted within the last two weeks from followed users (back-end/app.js)
- If following list is `0`, request is never made and specific error component loaded (front-end/FeedPage.js)

Since things aren't totally together, here are the following tests to ensure the db queries work and component loads:
- Isolating date, we see recipes loaded from within last two weeks (if I changed to last day it shows just the one)
image
- If the following list is set to a static list (e.g. id of user `ash`) it shows only recipes by `ash` (and thus not from `Mobkinz`, the other user who has made a recipe)
image
- By default, since following isn't merged fully / I couldn't find it, I screenshotted the error component that will show up should you attempt to test this
image

### CODE REVIEW

**Comment by Dendrobyte** [comment]
This resolves #373

**Review by JonathanSussman1 — APPROVED** [review]
Seems to work. Nice job!

**Review by amn493 — CHANGES_REQUESTED** [review]
You need to filter req.query.following to remove elements in the list that are `''`. Currently, this is causing a 500 error when trying to grab the recipes.

**Comment by Dendrobyte** [comment]
> 
> 
> You need to filter req.query.following to remove elements in the list that are `''`. Currently, this is causing a 500 error when trying to grab the recipes.

I tested passing in an array with at least one ID and with 0 because there's no way to pull an actual following at the moment. When is `''` ever going to be in the following array?

**Comment by amn493** [comment]
> > You need to filter req.query.following to remove elements in the list that are `''`. Currently, this is causing a 500 error when trying to grab the recipes.
> 
> I tested passing in an array with at least one ID and with 0 because there's no way to pull an actual following at the moment. When is `''` ever going to be in the following array? It'll cause a 500 if the length is 0 and if an id is invalid, but I figure checking if a user still exists comes further down the line.

I manually added someone to my following array to test. The way that you're passing the query string will always make the first value in the array `''`.

**Comment by Dendrobyte** [comment]
> 
> 
> > > You need to filter req.query.following to remove elements in the list that are `''`. Currently, this is causing a 500 error when trying to grab the recipes.
> > 
> > 
> > I tested passing in an array with at least one ID and with 0 because there's no way to pull an actual following at the moment. When is `''` ever going to be in the following array? It'll cause a 500 if the length is 0 and if an id is invalid, but I figure checking if a user still exists comes further down the line.
> 
> I manually added someone to my following array to test. The way that you're passing the query string will always make the first value in the array `''`.

Gotcha. I'll fix that query on the front-end then bc having an empty string is the thing to avoid as opposed to removing it later.

**Comment by amn493** [comment]
> > > > You need to filter req.query.following to remove elements in the list that are `''`. Currently, this is causing a 500 error when trying to grab the recipes.
> > > 
> > > 
> > > I tested passing in an array with at least one ID and with 0 because there's no way to pull an actual following at the moment. When is `''` ever going to be in the following array? It'll cause a 500 if the length is 0 and if an id is invalid, but I figure checking if a user still exists comes further down the line.
> > 
> > 
> > I manually added someone to my following array to test. The way that you're passing the query string will always make the first value in the array `''`.
> 
> Gotcha. I'll fix that query on the front-end then bc having an empty string is the thing to avoid as opposed to removing it later.

I wouldn't. I would keep the front end the way it is and filter on the backend.

**Comment by Dendrobyte** [comment]
> 
> 
> > > > > You need to filter req.query.following to remove elements in the list that are `''`. Currently, this is causing a 500 error when trying to grab the recipes.
> > > > 
> > > > 
> > > > I tested passing in an array with at least one ID and with 0 because there's no way to pull an actual following at the moment. When is `''` ever going to be in the following array? It'll cause a 500 if the length is 0 and if an id is invalid, but I figure checking if a user still exists comes further down the line.
> > > 
> > > 
> > > I manually added someone to my following array to test. The way that you're passing the query string will always make the first value in the array `''`.
> > 
> > 
> > Gotcha. I'll fix that query on the front-end then bc having an empty string is the thing to avoid as opposed to removing it later.
> 
> I wouldn't. I would keep the front end the way it is and filter on the backend.

Sure

**Review by amn493 — CHANGES_REQUESTED** [review]
It's still crashing, not sure why this time. Also, it's showing the "not following anyone" error message for all errors. Maybe change it so that it only uses that message when that's why there are no recipes to display? And shows the default message in case of a 500 of some other actual error?

**Comment by Dendrobyte** [comment]
- Forgot to add front-end adjustments for the date multiplier, so it was causing an error when the following list was > 0 and trying to subtract `undefined` from `Date.now()`
- Error message only shows "you're not following anyone" if the list length is 0 (prior to querying the back-end) which I imagine was not pushed due to me, well, not adding it 🙃

**Review by amn493 — APPROVED** [review]
Looks good now!

**Pull request merged**
