### PR TITLE
Allowing user to crop recipe picture and profile picture uploads

### LINKED ISSUE #464: Allowing user to crop/scale profile/recipe photo uploads (user story #458)
1. Display a modal when an image is uploaded to a user's profile page or a recipe page
2. Allow user to crop/resize said image and save final image to respective recipe/user document in database

### PR DESCRIPTION
**Pull request by JonathanSussman1**
- Resolves #464 
- As of now, cropped images are exported as blobs (binary data w/type) rather than .pngs or .jpegs. Can change this if needed, but functionality is all there

### CODE REVIEW

**Comment by JonathanSussman1** [comment]
Modal that shows up onChange of Bootstrap custom file form control:

Screen Shot 2021-04-25 at 3 51 17 PM

Screen Shot 2021-04-25 at 3 48 03 PM

**Review by Dendrobyte — APPROVED** [review]
Love it! Works beautifully and saves properly and whatnot, so I'll approve.

One comment, and this could be a later polish task or something to quickly do prior to merging if you agree. Since `Cancel` keeps the image there but not cropped, it feels like I'm cancelling the upload and don't have a choice to not crop the image. That being said, maybe
- Rename `Cancel` to `Don't Crop`, 'Cancel Crop', or something along those lines
- Rename `Cancel` to `Don't Crop` and add a third button called `Cancel Upload` that removes the file as well.

Second suggestion seems kinda extraneous, and the first suggestion is just semantics. Works well nonetheless- nice job!

**Review by amn493 — CHANGES_REQUESTED** [review]
This looks amazing, but as Mark said, I think that pressing cancel should remove the image from being uploaded. Also, we should restrict the cropping window so that the user is forced to crop their image to a square.

**Review by amn493 — APPROVED** [review]
Looks amazing!!

**Pull request merged**
