### PR TITLE
fixing badge

### PR DESCRIPTION
**Pull request by anvitayella**
Editing url for badge.

### CODE REVIEW

**Comment by Dendrobyte** [comment]
ah, didn't check the readme last time sorry

Any chance the text can be shortened? Not really a big deal and it does appear to be functional
image

**Comment by anvitayella** [comment]
I would, but I'm not sure where to change it?

**Comment by amn493** [comment]
I'll look into how to change it. Let's make it say `build`

**Comment by amn493** [comment]
It's this line in the `github-actions.yml` file: `name: Continuous Integration for RecipeBox`

**Review by amn493 — APPROVED** [review]
Looks great!

**Pull request merged**
