### PR TITLE
Searchbar Adjustments, RecipeBox Search Functionality

### LINKED ISSUE #525: Implement keyboard shortcuts
- Make it so that "Enter" will submit forms and such instead of having to go all the damn way over to click on it
- Make keyboard go away automatically after one tag is selected (just deselect from combo box)
- Remove drop shadow from the combo box search bar

### PR DESCRIPTION
**Pull request by Dendrobyte**
- Search now functional by tag and name on the RecipeBox page
- Hitting `Enter` will now submit all searchbar forms
- Hitting `Enter` acts as a submit action for logging in
- On the note of related issue #525 , dismissing the keyboard for mobile is an element of `react-native` as opposed to `react-dom`, and tapping anywhere outside the keyboard area appears to work fine for now. Unfocusing the text field was causing more issues than it was solving so I simply left the feature as it doesn't feel crucial.
- Removed inner shadow for the combo box searchbar when on mobile

<div style = "content-align: center;">

</div>

This issue resolves #525

### CODE REVIEW

**Comment by JonathanSussman1** [comment]
A few small things:
- The 'enter' shortcut is not working for me in either location (maybe because I have a Mac and we have 'return' instead of 'enter')
- RecipeBoxPage keyword/tag search doesn't seem to be filtering properly or sending requests to GET /filteredrecipes: 
Screen Shot 2021-05-03 at 12 10 19 PM
Screen Shot 2021-05-03 at 12 09 12 PM
Screen Shot 2021-05-03 at 12 09 04 PM

- Remove the multiple images functionality-in-progress i.e NewRecipePage.js from this PR (by the way let me know if you need to know anything about how cropping works for what you're doing)
- Remove console.log statements

**Review by JonathanSussman1 — DISMISSED** [review]
^

**Comment by Dendrobyte** [comment]
Uhh yikes.

I must have pushed some stuff alongside the mult images thing I was working on. I do have a crop question for you but I was gonna ask during class. It's just commented out so I didn't have to keep cropping an image each time I was testing the upload haha- not something I intended to keep commented out or changing or anything.

I'll re-request review once I make sure this is all working as intended locally. I should have checked the files changed beforehand sorry about that.

**Comment by Dendrobyte** [comment]
@JonathanSussman1 Would you mind trying again now? It's "again" working for me hitting enter on my laptop and phone. If you have a moment before class, I just want to make sure it wasn't something with my accidentally committed files.

Search bar should work with enter, combo box requires you to use arrow keys before choosing one and hitting enter. If it doesn't I'll look more into it, again just want to make sure it wasn't something half-baked in the committing error since it works on iPhone by hitting `Enter`. 

Thanks!

**Comment by JonathanSussman1** [comment]
The enter shortcut is working now 👌 👌 
And filtering in RecipeBoxPage is generally working, but with some search terms, an extraneous recipe appears that is not in my RecipeBox?
Screen Shot 2021-05-03 at 2 17 34 PM
Screen Shot 2021-05-03 at 2 17 09 PM

**Comment by JonathanSussman1** [comment]
Also I think it would be nice to have 'no recipes found' come up when no items in the RecipeBox meet search criteria such as is the case in BrowseRecipesPage

**Comment by Dendrobyte** [comment]
Ok so it was the commit stuff. Weird.

Anywho, I'll get on those and good suggestion- thanks!

**Comment by Dendrobyte** [comment]
Filter working properly and added a little "no recipes found" thing if, well, nothing is found! 
image

**Comment by amn493** [comment]
> Filter working properly and added a little "no recipes found" thing if, well, nothing is found!
> image

Can you change the css on this to match the browse recipes page?

**Review by amn493 — APPROVED** [review]
Teamwork

**Pull request merged**
