### PR TITLE
GET request to /usersbyid from frontend (AppSettings.js)

### LINKED ISSUE #169: Make a GET request to the /usersbyid API from the front-end (AppSettings.js) (User Story #158)
- Change Mockaroo API URL to actual URL.
- Include `ids` in request - `props.user.blockedUsers`

### PR DESCRIPTION
**Pull request by JonathanSussman1**
- resolves #169

### CODE REVIEW

**Review by anvitayella — APPROVED** [review]
All the changes look good to me!

**Comment by amn493** [comment]
Be careful with sending an array in the query string - it won't be processed properly. Check out #262 for a possible fix.

**Review by amn493 — CHANGES_REQUESTED** [review]
Be careful with sending an array in the query string - it won't be processed properly. Check out #262 for a possible fix.

**Comment by JonathanSussman1** [comment]
> Be careful with sending an array in the query string - it won't be processed properly. Check out #262 for a possible fix.

fixed!

**Comment by amn493** [comment]
The dependency arrays aren't accurate. The variable in the array should be such that when the variable's value changes, you want to make this axios request.

Also, you have a call to map that looks something like `.map(user => user)`. The only thing that call is doing is wasting time lmao

**Comment by amn493** [comment]
You need to pull from master to merge the newest version into this branch.

`git fetch origin`
`git pull origin master`

**Comment by amn493** [comment]
`onClick={() => setPostsNotifs(!postsNotifs)}` seems to have gotten deleted from the posts toggle switch

**Review by amn493 — APPROVED** [review]
Once that line is added, feel free to merge!

**Pull request merged**
