### PR TITLE
prevent blocked users from viewing followers and following lists

### LINKED ISSUE #211: Prevent a user from viewing followers/following pages of users who blocked them / who they have blocked (User Story #46)

### PR DESCRIPTION
**Pull request by oliviaedell**
Resolves #211 
* change follower/following number to 0
* display "no users found"

### CODE REVIEW

**Comment by JonathanSussman1** [comment]
Getting this error when I click on a blocked user's following or followers count:
Screen Shot 2021-04-20 at 4 34 25 PM
you might want to get omit that axios call to `usersbyid` under the condition that `userBlocked` is true

also on both pages, `slug` is the only thing that should be in the dependency array of the first `useEffect()` call, and `userBlocked` should be added to the dependency array of that second `useEffect()` call (@amn493 correct me if I'm wrong)

**Review by JonathanSussman1 — CHANGES_REQUESTED** [review]
.

**Comment by oliviaedell** [comment]
> Getting this error when I click on a blocked user's following or followers count:
> Screen Shot 2021-04-20 at 4 34 25 PM
> you might want to get omit that axios call to `usersbyid` under the condition that `userBlocked` is true
> 
> also on both pages, `slug` is the only thing that should be in the dependency array of the first `useEffect()` call, and `userBlocked` should be added to the dependency array of that second `useEffect()` call (@amn493 correct me if I'm wrong)

Looks like the error comes from a user with 0 followers or 0 following whether they're blocked or not, I checked with master and get the same error there. I can fix it on this branch before merging though.
I get linting errors when I change it back to just `slug` since dependency arrays should include all values referenced in `useEffect()`. the data is fetched once either way if you want me to change it back anyway but I don't think it makes a difference.
I'll see what I can do about skipping the axios call to `usersbyid` it's a little tricky since axios is async so the second `useEffect()` will be executed  and users fetched before `userBlocked` is changed to true 
 @JonathanSussman1 @amn493 let me know what you think

**Comment by Dendrobyte** [comment]
I blocked `@Myobkeenz` and I can still see the num of followers and following, but when I click on those they are empty. 
image

I haven't tried the other way around though. Also @JonathanSussman1 might be better to test to look for past issues that came up to double check that those are resolved?

**Review by amn493 — APPROVED** [review]

**Review by amn493 — COMMENTED** [review]
I resolved the merge conflicts and fixed a couple of bugs (as we discussed)

**Pull request merged**
