### PR TITLE
Route handler and GET request for feedrecipes

### PR DESCRIPTION
**Pull request by Dendrobyte**
Pushing mostly to make sure I did this right. Feeling fine about the route handler, but regarding the `get` request... Maybe some silly questions but to put me at ease:

- I don't need to pass anything in the front-end, right? Since that's all done in the route handler?
- Error checking probably needs to be done on the front-end as well

Lmk if that's the right way to go about doing this! I haven't tested the appearance and I'm more asking about conventionality I guess.

### CODE REVIEW

**Comment by Dendrobyte** [comment]
- Commented out recipebox because I have been ⭐procrastinating⭐ it. Tis my first task for Monday alongside whatever routes I claim next.
- Added async stuff to the actual get call because I forgot we do need to do that

**Comment by Dendrobyte** [comment]
GET requestion functions properly (e.g. calls mockaroo properly) and is tested with backend on port 4000.

**Review by amn493 — CHANGES_REQUESTED** [review]
A few notes:
- You might be better off grabbing the current time in the route handler on the back-end instead of passing it from the front-end in the query string (you won't have to deal with converting it from a string)
- Fields in a query string are separated by `&` not `?` (ex: `?field1=x&field2=y`)
- You don't need to be passing the user's id, you need to be passing their liked array (passing arrays is a little tricky, feel free to check out what I did in `BrowseRecipesPage.js`)

**Review by amn493 — CHANGES_REQUESTED** [review]
Looks good aside from one thing: in the request, `http://localhost:4000/feedrecipes?following=` should be `http://localhost:4000/feedrecipes?`

**Pull request merged**
