### PR TITLE
User story/347/task/368/recipesbyuser

### PR DESCRIPTION
**Pull request by Dendrobyte**
Unable to thoroughly test, but appears to be fine from existing data (e.g. if I log the request info, it successfully shows that `req.query.userID` is the matching ID to the mockaroo user pulled from). In other words, it pulls a value from the intended spot that matches the intended value.

Question remains: it appears the database shows `ObjectId("####")`... does that change anything?
image

### CODE REVIEW

**Comment by Dendrobyte** [comment]
Looks like the followbutton thing is resolved in #415 so merge that first I suppose then I'll resolve any conflicts here.

**Review by amn493 — COMMENTED** [review]
There shouldn't be an underscore in `user.id`

**Comment by Dendrobyte** [comment]
Putting in an existing user id retrieves proper recipes 🔥
image

**Review by amn493 — CHANGES_REQUESTED** [review]
This looks great! Can you just change one thing? Before sending back the recipes, can you sort them from newest to oldest?

**Review by amn493 — APPROVED** [review]

**Pull request merged**
