### PR TITLE
Prevent user from seeing profiles of users they have blocked or who have blocked them

### LINKED ISSUE #222: Prevent a user from viewing profiles of users who have blocked them / who they have blocked (User Story #46)
When a user is blocked, they should not be able to view the profile of the person who blocked them.

E.g. if Mark blocks Jonathan, Jonathan should not be able to view Mark's profile.

### PR DESCRIPTION
**Pull request by oliviaedell**
resolves #222 
blocked profile should have:
* 0s for recipe, follower, following counts
* No follow button
* "No Recipes" error component 

commits are weird because of rebase

### CODE REVIEW

**Review by JonathanSussman1 — CHANGES_REQUESTED** [review]
seems to work solidly but can u disable clicking the following/follower count buttons on blocked users' profiles? I can still go through and see my blocked users' followers and following list despite the counts being displayed as 0

**Comment by oliviaedell** [comment]
> seems to work solidly but can u disable clicking the following/follower count buttons on blocked users' profiles? I can still go through and see my blocked users' followers and following list despite the counts being displayed as 0

Yeah the followers/following pages for blocked users are in a different branch

**Comment by JonathanSussman1** [comment]
> > seems to work solidly but can u disable clicking the following/follower count buttons on blocked users' profiles? I can still go through and see my blocked users' followers and following list despite the counts being displayed as 0
> 
> Yeah the followers/following pages for blocked users are in a different branch #447 @JonathanSussman1

oh my bad. Should be good to merge then in that case

**Review by JonathanSussman1 — APPROVED** [review]

**Review by amn493 — CHANGES_REQUESTED** [review]
Followers / Following links should not be clickable. Also, don't use the error component. Use the 'no recipes yet' message that gets displayed when a user has no posts.

**Comment by JonathanSussman1** [comment]
I think this is looking good to merge. @amn493 ?

**Review by amn493 — APPROVED** [review]
Looks good to me

**Pull request merged**
